name: Chocolatine

on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
  pull_request:
    branches-ignore:
      - 'ga-ignore-*'
env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-PAR-2-1-chocolatine-thomas.tran.git
  EXECUTABLES: "my_sokoban"
jobs:
  check_repository_cleanliness:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Check useless files
        run:  |
          var=0
          find . -name "*.a" -o -name "*.o" -o -name "#*#" -o -name "*~" -o -name "*pain_au_chocolat*" -o -name "*.so" -o -name "*.gcno" -o -name "*.gcda" -o -name "*.gcovr" |
          while read FILE;
          do
          var=1
          echo "::error title=Unwanted file detected,file=$FILE,line=10,col=15:: $FILE";
          done
          if [ $var -eq "1" ];
          then
            exit 1
          fi
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Build project
        run: make
      - name: Clean build
        run: make clean
      - name: Check executables
        run:  |
          filename="$EXECUTABLES"
          IFS=','
          read -ra ADDR <<< "$filename"
          for i in "${ADDR[@]}"
          do
          [[ ! -f "$i" || ! -x "$i" ]] && echo "::error::$i is missing or not a executable." && exit 1
          done
          exit 0
  run_tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Units test
        run: make tests_run
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}
