name: Chocolatine
on:
  push:
    branches-ignore:
      - 'ga-ignore-*'
env:
  MIRROR_URL: git@github.com:EpitechPromo2026/B-DOP-200-PAR-2-1-chocolatine-thomas.tran.git
  EXECUTABLES: "my_sokoban"
jobs:
  check_program_compilation:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
        with:
            fetch-depth: 0
      - name: Build project
        run: make
      - name: Clean build
        run: make clean
      - name: Check executables
        run: |
          filename="$EXECUTABLES"
          IFS=','
          read -ra ADDR <<< "$filename"
          for i in "${ADDR[@]}"
          do
          [ ! -f "$i" ] && echo "::error::$i is missing."
          done
  run_tests:
    runs-on: ubuntu-latest
    container: epitechcontent/epitest-docker:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Units test
        run: make tests_run
  push_to_mirror:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pixta-dev/repository-mirroring-action@v1
        with:
          target_repo_url: ${{ env.MIRROR_URL }}
          ssh_private_key:
            ${{ secrets.PRIVATE_KEY }}
